# Generated by Django 5.0.6 on 2024-06-22 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelexpense',
            name='user',
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='user_country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_visit_country', to='countries.visitedcountries'),
            preserve_default=False,
        ),
    ]
