default_stages:
  - commit
exclude: docs|node_modules|migrations|.git|.tox
fail_fast: false
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
  - hooks:
      - id: flake8
        args:
          - --config=setup.cfg
        additional_dependencies:
          - flake8-isort
        language_version: python3.9
    repo: https://github.com/pycqa/flake8
    rev: 5.0.4
  - hooks:
      - id: isort
        args: [--settings-path=setup.cfg, --skip-glob='**/**/**/migrations']
        files: .
    repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
  - hooks:
      - id: bandit
        args: [-r, -lll, -i]
        files: .
    repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.29.5
  # - hooks:
  #     - id: eslint
  #       name: Check eslint and standard coding style
  #       entry: npx lint-staged --no-stash --cwd ./frontend
  #       language: system
  #   repo: local
